
package servisi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CasServisService", targetNamespace = "http://servisi/", wsdlLocation = "http://localhost:5001/Cas?wsdl")
public class CasServisService
    extends Service
{

    private final static URL CASSERVISSERVICE_WSDL_LOCATION;
    private final static WebServiceException CASSERVISSERVICE_EXCEPTION;
    private final static QName CASSERVISSERVICE_QNAME = new QName("http://servisi/", "CasServisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5001/Cas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CASSERVISSERVICE_WSDL_LOCATION = url;
        CASSERVISSERVICE_EXCEPTION = e;
    }

    public CasServisService() {
        super(__getWsdlLocation(), CASSERVISSERVICE_QNAME);
    }

    public CasServisService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CASSERVISSERVICE_QNAME, features);
    }

    public CasServisService(URL wsdlLocation) {
        super(wsdlLocation, CASSERVISSERVICE_QNAME);
    }

    public CasServisService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CASSERVISSERVICE_QNAME, features);
    }

    public CasServisService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CasServisService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICasServis
     */
    @WebEndpoint(name = "CasServisPort")
    public ICasServis getCasServisPort() {
        return super.getPort(new QName("http://servisi/", "CasServisPort"), ICasServis.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICasServis
     */
    @WebEndpoint(name = "CasServisPort")
    public ICasServis getCasServisPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servisi/", "CasServisPort"), ICasServis.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CASSERVISSERVICE_EXCEPTION!= null) {
            throw CASSERVISSERVICE_EXCEPTION;
        }
        return CASSERVISSERVICE_WSDL_LOCATION;
    }

}
