
package servisi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMaterijalServis", targetNamespace = "http://servisi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMaterijalServis {


    /**
     * 
     * @param arg0
     * @return
     *     returns servisi.Materijal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preuzmiMaterijal", targetNamespace = "http://servisi/", className = "servisi.PreuzmiMaterijal")
    @ResponseWrapper(localName = "preuzmiMaterijalResponse", targetNamespace = "http://servisi/", className = "servisi.PreuzmiMaterijalResponse")
    @Action(input = "http://servisi/IMaterijalServis/preuzmiMaterijalRequest", output = "http://servisi/IMaterijalServis/preuzmiMaterijalResponse")
    public Materijal preuzmiMaterijal(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<servisi.Materijal>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preuzmiMaterijale", targetNamespace = "http://servisi/", className = "servisi.PreuzmiMaterijale")
    @ResponseWrapper(localName = "preuzmiMaterijaleResponse", targetNamespace = "http://servisi/", className = "servisi.PreuzmiMaterijaleResponse")
    @Action(input = "http://servisi/IMaterijalServis/preuzmiMaterijaleRequest", output = "http://servisi/IMaterijalServis/preuzmiMaterijaleResponse")
    public List<Materijal> preuzmiMaterijale(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
