package gui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.List;
import javax.swing.ImageIcon;
import servisi.CasServisService;
import servisi.ICasServis;
import servisi.Materijal;
import utils.Konverter;

/**
 *
 * @author zi
 */

public class CasForm extends javax.swing.JFrame {
	
	private ICasServis servis;
	private List<Materijal> materijali;
	private int index;
	
	/**
	 * Creates new form CasForm
	 */
	public CasForm() {
		initComponents();
	}
	
	public void selektujLekciju(int razred, int lekcija) {
		servis = new CasServisService().getCasServisPort();
		materijali = servis.preuzmiMaterijale(razred, lekcija);
		index = 0;
		if(materijali.size() > 0)
			prikaziSliku();
	}
	
	private void prikaziSliku() {
		try {
			byte[] slika = materijali.get(index).getSlika();
			BufferedImage biSlika = Konverter.byteArrayToImage(slika);
			Image sSlika = biSlika.getScaledInstance(lblSlika.getWidth(),
													 lblSlika.getHeight(),
													 Image.SCALE_SMOOTH);
			lblSlika.setIcon(new ImageIcon(sSlika));
		} catch (IOException ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSledeci = new javax.swing.JButton();
        btnPrethodni = new javax.swing.JButton();
        lblSlika = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ЧАС");

        btnSledeci.setText(" > ");
        btnSledeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSledeciActionPerformed(evt);
            }
        });

        btnPrethodni.setText(" < ");
        btnPrethodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrethodniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 847, Short.MAX_VALUE)
                        .addComponent(btnPrethodni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSledeci))
                    .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSledeci)
                    .addComponent(btnPrethodni))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSledeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSledeciActionPerformed
        if(index < materijali.size() - 1) {
			index++;
			prikaziSliku();
		}
    }//GEN-LAST:event_btnSledeciActionPerformed

    private void btnPrethodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrethodniActionPerformed
        if(index > 0) {
			index--;
			prikaziSliku();
		}
    }//GEN-LAST:event_btnPrethodniActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrethodni;
    private javax.swing.JButton btnSledeci;
    private javax.swing.JLabel lblSlika;
    // End of variables declaration//GEN-END:variables
}
