package gui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author zi
 */

public class MainForm extends javax.swing.JFrame {

	/**
	 * Creates new form MainForm
	 */
	public MainForm() {
		initComponents();
	}
	
	public void prijavaNaCas(int razred, int lekcija) {
		CasForm frmCas = new CasForm();
		frmCas.setDefaultCloseOperation(EXIT_ON_CLOSE);
		frmCas.setVisible(true);
		frmCas.selektujLekciju(razred, lekcija);
		setVisible(false);
	}
	
	public void prijavaNaKviz(String ime, String prezime) {
		KvizForm frmKviz = new KvizForm();
		frmKviz.setDefaultCloseOperation(EXIT_ON_CLOSE);
		if(frmKviz.prijava(ime, prezime)) {
			frmKviz.setVisible(true);
			setVisible(false);
			
			RangListaForm frmRangLista = new RangListaForm();
			frmRangLista.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "Није могуће пријавити се на квиз");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCas = new javax.swing.JButton();
        btnKviz = new javax.swing.JButton();
        btnKontrolni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ЧАС");

        btnCas.setText("ЧАС");
        btnCas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasActionPerformed(evt);
            }
        });

        btnKviz.setText("КВИЗ");
        btnKviz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKvizActionPerformed(evt);
            }
        });

        btnKontrolni.setText("КОНТРОЛНИ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKontrolni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKviz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKviz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKontrolni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("MainForm");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasActionPerformed
		PrijavaCasDialog dlgPrijavaCas = new PrijavaCasDialog(this, true);
		dlgPrijavaCas.setVisible(true);
    }//GEN-LAST:event_btnCasActionPerformed

    private void btnKvizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKvizActionPerformed
		PrijavaKvizDialog dlgPrijavaKviz = new PrijavaKvizDialog(this, true);
		dlgPrijavaKviz.setVisible(true);
    }//GEN-LAST:event_btnKvizActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			com.jtattoo.plaf.mint.MintLookAndFeel.setTheme("Mint");
			UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCas;
    private javax.swing.JButton btnKontrolni;
    private javax.swing.JButton btnKviz;
    // End of variables declaration//GEN-END:variables
}
