package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import servis.CasServisService;
import servis.ICasServis;
import servis.Takmicar;

/**
 *
 * @author zi
 */

public class RangListaForm extends javax.swing.JFrame {
	
	private ICasServis servis;
	
	private List<Takmicar> rangLista;
	
	private DefaultTableModel modelRangLista;
	
	private Timer tajmer;

	/**
	 * Creates new form RangListaForm
	 */
	public RangListaForm() {
		servis = new CasServisService().getCasServisPort();
		initModels();
		initComponents();
		postaviTajmere();
	}
	
	private void initModels() {
		modelRangLista = new DefaultTableModel(
			new Object[][] {},
			new String[] {
				"Име",
				"Презиме",
				"Бодови"
			}
		) {
			@Override
			public boolean isCellEditable(int i, int i1) {
				return false;
			}
			
		};
	}
	
	public void postaviTajmere() {
		tajmer = new Timer(1000, new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent ae) {
				SwingUtilities.invokeLater(new Runnable() {
					@Override
					public void run() {
						osveziRangListu();
					}
				});
			}
		});
		tajmer.setRepeats(true);
		tajmer.start();
	}
	
	public void osveziRangListu() {
		rangLista = servis.preuzmiRangListu();
		
		while(modelRangLista.getRowCount() > 0) {
			modelRangLista.removeRow(0);
		}
		
		for(Takmicar takmicar : rangLista) {
			modelRangLista.addRow(new Object[] {
				takmicar.getIme(),
				takmicar.getPrezime(),
				takmicar.getBodovi()
			});
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRangLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ранг листа");

        tblRangLista.setModel(modelRangLista);
        tblRangLista.setName("tblRangLista"); // NOI18N
        jScrollPane1.setViewportView(tblRangLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRangLista;
    // End of variables declaration//GEN-END:variables
}
